### ISSUE TITLE
Spotfinder (GPU and Standalone) missing reflections

### ISSUE THREAD

**Issue by dimitrivlachos** [ndevenish/miniapp#9]
Even though the standalone spotfinder is meant to directly emulate what is done in dials, it does not always produce the same results. Since this is what has been used to validate the GPU spotfinder, this, too, deviates from DIALS proper.

For example, in `/dls/i03/data/2024/cm37235-2/xraycentring/TestInsulin/ins_14/ins_14_24.nxs` : `image 3`, DIALS finds multiple spots within the 4-40Å range, but both the standalone and GPU-based spotfinders do not.

**Comment by dimitrivlachos** [comment]
### GPU Spotfinder:
![image_00002](https://github.com/ndevenish/miniapp/assets/86776716/669ce4b8-47aa-4fb4-90d7-8e01c01d5c82)
vs.
### DIALS find_spots:
![image](https://github.com/ndevenish/miniapp/assets/86776716/cd2de058-5763-4002-8dfe-f6d6a4834ea1)

**Comment by graeme-winter** [comment]
I believe that this code performs the same algorithm as `dials.find_spots algorithm=dispersion` for the signal filtering:

https://gist.github.com/graeme-winter/16c5877e6ecde1f9a4130562ef7580a0

**Comment by dimitrivlachos** [comment]
Yes, the DIALS processing was done with:
`dials.find_spots imported.expt disable_parallax_correction=True algorithm=dispersion d_min=4 d_max=40`

**Comment by dimitrivlachos** [comment]
> I believe that this code performs the same algorithm as `dials.find_spots algorithm=dispersion` for the signal filtering:
> 
> https://gist.github.com/graeme-winter/16c5877e6ecde1f9a4130562ef7580a0

Yes, the DIALS processing was done with:
`dials.find_spots imported.expt disable_parallax_correction=True algorithm=dispersion d_min=4 d_max=40`
